### ISSUE TITLE
schema rating

### ISSUE THREAD

**Issue by joernroeder** [elementous/rating-manager-lite#1]
Hey,
i stumbled over this tiny wp plugin and would love to use it for a blog i'm building right now. But after looking into the code i noticed that the schema tags are hardcoded as `schema.org/Review` by a `schema.org/Person`. As it's using the average rating for the current `post_id` i'm suggesting to change it to http://schema.org/AggregateRating as this is whats actually going on [here](https://github.com/elementous/rating-manager-lite/blob/master/includes/classes/rating-manager.class.php#L707).

**Comment by dominykasgel** [comment]
Thank you! We'll take a closer look :)

**Comment by joernroeder** [comment]
@dominykasgel i've also updated and merged AggregateRating in my repo…
